Backend: Vivado
Board: null
ClockPeriod: 10.0
HLSConfig:
  LayerName:
    dense1:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
      Trace: false
    dense2:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
      Trace: false
    input_1:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ap_ufixed<10,0>
      ReuseFactor: 1
      Trace: false
    softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
      exp_table_t: ap_fixed<18,8>
      inv_table_t: ap_fixed<18,4>
      table_size: 1024
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_foldbatchnorm_vivado_prj/keras_model.h5'
OutputDir: hls4ml_foldbatchnorm_vivado_prj
OutputPredictions: null
ProjectName: myproject
Stamp: 5f7D5b6B
XilinxPart: XC7A100T
