Backend: Vivado
ClockPeriod: 10.0
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
    dense1:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
      Trace: false
    dense1_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
      table_size: 1024
      table_t: ap_fixed<18,8>
    dense2:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<5,1>
      ReuseFactor: 1
      Trace: false
    dense2_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
      table_size: 1024
      table_t: ap_fixed<18,8>
    input_1:
      Precision:
        result: ap_fixed<16,6>
      Trace: false
    relu1:
      Precision:
        result: ap_ufixed<10,0>
      ReuseFactor: 1
      Trace: false
    relu1_quantized_relu(10,0):
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
      table_size: 1024
      table_t: ap_fixed<18,8>
    softmax:
      Precision: ap_fixed<16,6>
      ReuseFactor: 1
      Trace: false
      exp_table_t: ap_fixed<18,8>
      inv_table_t: ap_fixed<18,4>
      table_size: 1024
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_vivado_prj/keras_model.h5'
OutputDir: hls4ml_vivado_prj
OutputPredictions: null
Part: XC7A100T
ProjectName: myproject
Stamp: 2358bbbD
